### ISSUE TITLE
Only Location is 'Virtual' - Low

### ISSUE THREAD

**Issue by asmart3** [esolache/TBR#15]
In some of the sessions already listed before starting the app (presumably dummy data), there are multiple locations listed such as coffee shop or library. However, the only available option when signing up for a tutor session is virtual. I would suggest adding a text input much like the 'Description' portion of signing up for a session instead of a drop down list.

Severity: Low

**Comment by emwinckler** [comment]
Because of the pandemic, we're currently limiting location to being virtual.  It's true that the other locations are just dummy data.  When the pandemic is over, other locations may be added and once the messaging service is implemented then students and tutors may discuss alternatives.  For now, limiting locations to a set list.
